
# tap repositories and their packages

tap 'homebrew/core'
brew 'apr'
brew 'apr-util'
brew 'aws-iam-authenticator'
brew 'bitwarden-cli'
brew 'boost'
brew 'brotli'
brew 'c-ares'
brew 'ca-certificates'
brew 'carthage'
brew 'coreutils'
brew 'double-conversion'
brew 'fastlane'
brew 'fmt'
brew 'folly'
brew 'gdbm'
brew 'gettext'
brew 'gflags'
brew 'git'
brew 'glog'
brew 'gmp'
brew 'go'
brew 'helm'
brew 'icu4c'
brew 'jemalloc'
brew 'jmeter'
brew 'jq'
brew 'kind'
brew 'krb5'
brew 'kubernetes-cli'
brew 'libev'
brew 'libevent'
brew 'libnghttp2'
brew 'libuv'
brew 'libyaml'
brew 'lz4'
brew 'macos-term-size'
brew 'mas'
brew 'minikube'
brew 'mosh'
brew 'mpdecimal'
brew 'mysql'
brew 'ncurses'
brew 'nghttp2'
brew 'node'
brew 'oniguruma'
brew 'openjdk'
brew 'openjdk@11'
brew 'openssl@1.1'
brew 'pcre'
brew 'pcre2'
brew 'postgresql'
brew 'protobuf'
brew 'python@3.10'
brew 'python@3.8'
brew 'python@3.9'
brew 'readline'
brew 'ruby'
brew 'ruby@2.7'
brew 'six'
brew 'slides'
brew 'snappy'
brew 'sqlite'
brew 'subversion'
brew 'tcl-tk'
brew 'terminal-notifier'
brew 'terraform'
brew 'tilt'
brew 'utf8proc'
brew 'watchman'
brew 'xz'
brew 'yarn'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-fast-syntax-highlighting'
brew 'zstd'

tap 'homebrew/bundle'

tap 'homebrew/cask-drivers'

tap 'homebrew/cask-fonts'
cask 'font-3270'
cask 'font-hack-nerd-font'

tap 'homebrew/cask-versions'
cask 'firefox-developer-edition'

tap 'homebrew/services'

tap 'homebrew/cask'
cask 'alfred'
cask 'discord'
cask 'iterm2'
cask 'postman'
cask 'react-native-debugger'
cask 'rectangle'
cask 'slack'
cask 'virtualbox'
cask 'ytmdesktop-youtube-music'

tap 'ankitpokhrel/jira-cli'
brew 'jira-cli'

tap 'bufbuild/buf'
brew 'buf'

tap 'hashicorp/tap'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'romkatv/powerlevel10k'
brew 'powerlevel10k'

tap 'tilt-dev/tap'

tap 'wix/brew'
brew 'applesimutils'

# App Store applications
mas 'Bitwarden (1.30.0)', id: 1352778147
mas 'HealthGuard (4.0)', id: 1529162295
mas 'Xcode (13.2.1)', id: 497799835
